In [1]:
#Importing important libraries
import pandas as pd
import numpy as np

In [3]:
#reading the csv
df=pd.read_csv("/content/FoodBalanceSheets_E_Africa_NOFLAG.csv",encoding="latin-1")

In [4]:
df.head()

,Area Code,Area,Item Code,Item,Element Code,Element,Unit,Y2014,Y2015,Y2016,Y2017,Y2018
0,4,Algeria,2501,Population,511,Total Population - Both sexes,1000 persons,38924.00,39728.00,40551.00,41389.00,42228.00
1,4,Algeria,2501,Population,5301,Domestic supply quantity,1000 tonnes,0.00,0.00,0.00,0.00,0.00
2,4,Algeria,2901,Grand Total,664,Food supply (kcal/capita/day),kcal/capita/day,3377.00,3379.00,3372.00,3341.00,3322.00
3,4,Algeria,2901,Grand Total,674,Protein supply quantity (g/capita/day),g/capita/day,94.90,94.35,94.72,92.82,91.83
4,4,Algeria,2901,Grand Total,684,Fat supply quantity (g/capita/day),g/capita/day,80.06,79.36,77.40,80.19,77.28

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60943 entries, 0 to 60942
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Area Code     60943 non-null  int64
 1   Area          60943 non-null  object
 2   Item Code     60943 non-null  int64
 3   Item          60943 non-null  object
 4   Element Code  60943 non-null  int64
 5   Element       60943 non-null  object
 6   Unit          60943 non-null  object
 7   Y2014         59354 non-null  float64
 8   Y2015         59395 non-null  float64
 9   Y2016         59408 non-null  float64
 10  Y2017         59437 non-null  float64
 11  Y2018         59507 non-null  float64
dtypes: float64(5), int64(3), object(4)
memory usage: 5.6+ MB

In [25]:
#Q5
unique_values = df['Area'].nunique()
unique_values

49

In [82]:
# Q6

result = df.loc[(df['Element'] == 'Protein supply quantity (g/capita/day)') & (df['Area'] == 'Madagascar'), 'Y2015'].sum()

# Print the result
print('Total Protein supply quantity in Madagascar in 2015:',result)

Total Protein supply quantity in Madagascar in 2015: 173.04999999999998

In [37]:
#Q7

gp=df.groupby(['Y2017','Area'])['Area'].sum()
gp

Y2017      Area
-1582.0    Egypt                                           EgyptEgypt
-1200.0    Mozambique                                      Mozambique
-1159.0    Mozambique                                      Mozambique
-865.0     United Republic of Tanzania    United Republic of Tanzania
-860.0     United Republic of Tanzania    United Republic of Tanzania
                                                     ...
 96443.0   Egypt                                                Egypt
 106400.0  Ethiopia                                          Ethiopia
 112625.0  Nigeria                                            Nigeria
 117702.0  Nigeria                                            Nigeria
 190873.0  Nigeria                                            Nigeria
Name: Area, Length: 14773, dtype: object

In [75]:
sc = df[['Y2017', 'Area']]
sum_a = sc.groupby('Area').sum()
h_sum = sum_a.idxmax()[0]
print("Area with the highest sum in 2017:", h_sum)

Area with the highest sum in 2017: Nigeria

In [39]:
#Q8
df.describe()

,Area Code,Item Code,Element Code,Y2014,Y2015,Y2016,Y2017,Y2018
count,60943.000000,60943.000000,60943.000000,59354.000000,59395.000000,59408.000000,59437.000000,59507.000000
mean,134.265576,2687.176706,3814.856456,134.196282,135.235966,136.555222,140.917765,143.758381
std,72.605709,146.055739,2212.007033,1567.663696,1603.403984,1640.007194,1671.862359,1710.782658
min,4.000000,2501.000000,511.000000,-1796.000000,-3161.000000,-3225.000000,-1582.000000,-3396.000000
25%,74.000000,2562.000000,684.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,136.000000,2630.000000,5142.000000,0.090000,0.080000,0.080000,0.100000,0.070000
75%,195.000000,2775.000000,5511.000000,8.340000,8.460000,8.430000,9.000000,9.000000
max,276.000000,2961.000000,5911.000000,176405.000000,181137.000000,185960.000000,190873.000000,195875.000000

In [77]:
mean_2017 = df['Y2017'].mean()
std_dev_2017 = df['Y2017'].std()

mean_2017_rounded = round(mean_2017, 2)
std_dev_2017_rounded = round(std_dev_2017, 2)

print("Mean for the year 2017:", mean_2017_rounded)
print("Standard deviation for the year 2017:", std_dev_2017_rounded)

Mean for the year 2017: 140.92
Standard deviation for the year 2017: 1671.86

In [47]:

#Q10
df1 = df[['Y2014', 'Y2015', 'Y2016', 'Y2017', 'Y2018', 'Element Code']]

correlation_with_column1 = df1.corr()
correlation_with_column1

                 Y2014     Y2015     Y2016     Y2017     Y2018  Element Code
Y2014         1.000000  0.994647  0.996081  0.995230  0.994872      0.024457
Y2015         0.994647  1.000000  0.995739  0.988048  0.988208      0.023889
Y2016         0.996081  0.995739  1.000000  0.992785  0.992757      0.023444
Y2017         0.995230  0.988048  0.992785  1.000000  0.998103      0.024254
Y2018         0.994872  0.988208  0.992757  0.998103  1.000000      0.024279
Element Code  0.024457  0.023889  0.023444  0.024254  0.024279      1.000000

In [84]:
#Q12

wine=df.groupby('Item')[['Y2015','Y2018']].sum()
print("Total sum of Wine produced in 2015 and 2018 respectively:", wine)

Total sum of Wine produced in 2015 and 2018 respectively:                          Y2015      Y2018
Item
Alcohol, Non-Food      2180.00    2293.00
Alcoholic Beverages   98783.72   97847.27
Animal Products       11811.73   11578.61
Animal fats          200675.72  269648.27
Apples and products   10559.15    9640.51
...                        ...        ...
Vegetables, Other    158104.08  163987.21
Vegetal Products     107064.17  107775.39
Wheat and products   234710.51  242645.19
Wine                   4251.81    4039.32
Yams                 203151.78  221272.09

[119 rows x 2 columns]

In [85]:
#Q14

sel_c = df[['Y2017', 'Area']]

sum_2017 = sel_c.groupby('Area').sum()

low_in = sum_2017['Y2017'].nsmallest(7).index[-1]

print("the 7th lowest sum in 2017:", low_in)

the 7th lowest sum in 2017: Guinea-Bissau

In [67]:
#Q17

# Filter the DataFrame for rows where 'Element' is 'Processing'
processing_2017 = df[(df['Element'] == 'Processing') & (df['Y2017'] == 2017)]

wine=processing_2017.groupby('Element').sum()
wine

Empty DataFrame
Columns: [Area Code, Area, Item Code, Item, Element Code, Unit, Y2014, Y2015, Y2016, Y2017, Y2018]
Index: []

In [ ]:
total number and percentage of missing data in 2014 to 3 decimal places

In [72]:
#Q18
missing_2014 = df['Y2014'].isna().sum()

total_rows = len(df)

percentage_missing_2014 = (missing_2014 / total_rows) * 100

print("Total number of missing data in 2014:", missing_2014)
print("Percentage of missing data in 2014: {:.3f}%".format(percentage_missing_2014))

Total number of missing data in 2014: 1589
Percentage of missing data in 2014: 2.607%